name: Rust

# This workflow runs any time an push or pull request is made to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    
    # Updates and sets the rust toolchain to either stable, beta or nightly
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    
    # Build the project
    - name: Build
      run: cargo build --verbose
      
     # Test the project 
    - name: Run tests
      run: cargo test --verbose
